version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  lint:
    docker:
      - image: circleci/node:8.11.4
    steps:
      - checkout
      - run: npm install
      - run: npm run lerna bootstrap
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:8.11.4
    steps:
      - checkout
      - run: npm install
      - run: npm run lerna bootstrap
      - run: npm run test
      - codecov/upload:
          file: .coverage/*.json
  deploy-docs:
    docker:
      - image: circleci/node:8.11.4
    steps:
      - checkout
      - run: cd website && npm install && npm run build && cp -R build/tezos-ts ../dist
      - run: npm install
      - run: npm run lerna -- bootstrap
      - run: npm run lerna run build
      - run: npm run build-docs
      - run: cd packages/tezos-ts-react-components && npm run build-storybook -- -o ../../dist/react-storybook
      - run: cd dist && touch .nojekyll && echo 'tezos-ts.io' > CNAME
      - run:
          command: |
            git config user.email "ci-build@ecadlabs.com"
            git config user.name "ci-build"
            npm run gh-pages -- --dist dist --dotfiles --silent --repo https://$GITHUB_TOKEN@github.com/ecadlabs/tezos-ts.git
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - lint
      - test
      - deploy-docs:
          filters:
            branches:
              only: master

